# Generated by Django 5.2.7 on 2025-10-26 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Empleado')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del Empleado')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto (Ej: Diseñador, Desarrollador)')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Teléfono')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega Estimada')),
                ('id_campaña', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Campaña Asociada')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='app_empleado.empleado', verbose_name='Empleado Asignado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['fecha_entrega'],
            },
        ),
    ]
